-- +goose Up
CREATE TABLE POSTS (
    ID UUID PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    PUBLISHED_AT TIMESTAMP NOT NULL,
    URL TEXT NOT NULL UNIQUE,
    FEED_ID UUID NOT NULL REFERENCES FEEDS(ID) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE POSTS;